version: 2

project_name: kubeexec

builds:
  - main: ./cmd/kubeexec
    binary: kubeexec
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos: [darwin, linux]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    files:
      - completion/kubeexec.bash
      - completion/_kubeexec
      - completion/kubeexec.fish

release:
  github:
    owner: estebanmilaho
    name: kubeexec
  replace_existing_artifacts: true

brews:
  - name: kubeexec
    homepage: https://github.com/estebanmilaho/kubeexec
    description: FZF-based kubectl exec into pods
    license: Apache-2.0
    repository:
      owner: estebanmilaho
      name: homebrew-kubeexec
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    install: |
      bin.install "kubeexec"
      bash_completion.install "completion/kubeexec.bash" => "kubeexec"
      zsh_completion.install "completion/_kubeexec"
      fish_completion.install "completion/kubeexec.fish"
    test: |
      system "#{bin}/kubeexec", "-version"

krews:
  - name: kubeexec
    ids:
      - default
    homepage: https://github.com/estebanmilaho/kubeexec
    short_description: "Fast `kubectl exec` with fuzzy pod selection."
    description: "Select a pod with fzf and run kubectl exec (shell or command) in it."
    url_template: "https://github.com/estebanmilaho/kubeexec/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    skip_upload: true
