apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: xc
spec:
  version: "{{ .TagName }}"
  homepage: "https://github.com/estebanmilaho/kubeexec"
  shortDescription: "Fast `kubectl exec` with fuzzy pod selection."
  description: "Select a pod with fzf and run kubectl exec (shell or command) in it."
  files:
    - from: LICENSE
      to: .
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/estebanmilaho/kubeexec/releases/download/{{ .TagName }}/kubeexec_{{ .TagName | trimPrefix \"v\" }}_darwin_amd64.tar.gz" .TagName | indent 6}}
      bin: kubeexec
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/estebanmilaho/kubeexec/releases/download/{{ .TagName }}/kubeexec_{{ .TagName | trimPrefix \"v\" }}_darwin_arm64.tar.gz" .TagName | indent 6}}
      bin: kubeexec
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/estebanmilaho/kubeexec/releases/download/{{ .TagName }}/kubeexec_{{ .TagName | trimPrefix \"v\" }}_linux_amd64.tar.gz" .TagName | indent 6}}
      bin: kubeexec
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/estebanmilaho/kubeexec/releases/download/{{ .TagName }}/kubeexec_{{ .TagName | trimPrefix \"v\" }}_linux_arm64.tar.gz" .TagName | indent 6}}
      bin: kubeexec
